org.gradle.jvmargs=-Xmx2G

minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.15.10
# Mod Properties
mod_version=1.0.4+1.20.1
maven_group=dev.mayaqq
archives_base_name=spectrum-jetpacks
mod_id=spectrumjetpacks
# Dependencies
fabric_version=0.92.2+1.20.1
spectrum_version=1.8.1
rei_version=12.0.634
emi_version=1.0.24+1.20.1
trinkets_version=3.7.1
cloth_config_version=11.1.106
modmenu_version=7.2.1
matchbooks_version=1.20-SNAPSHOT
fractal_version=1.2.0

# Recipe Viewer (must be EMI, REI or disabled)
recipe_viewer=EMI